### ISSUE TITLE
Upload wheels for version 2.3

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pixel_clusterizer#1]

**Comment by DavidLP** [comment]
The clusterizer is a "pure python" package. What should a wheel do?

**Comment by DavidLP** [comment]
Does not make sense to me to create a wheel.

**Comment by laborleben** [comment]
since it is the new standard. Just a thought. Pure python or not is not relevant since wheel can be universal.

**Comment by DavidLP** [comment]
True. Ok, i will add autoupload the wheel on tags for travis.

**Comment by laborleben** [comment]
Even better :-)

**Comment by DavidLP** [comment]
Let's assume it work like mentioned here https://docs.travis-ci.com/user/deployment/pypi
