### ISSUE TITLE
Warning during usage of sdist package

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pixel_clusterizer#11]
The sdist package (pixel_clusterizer-3.1.2.tar.gz) is issuing warnings during usage:
```
....c:\users\jejan\dev\pixel_clusterizer\pixel_clusterizer\__init__.py:3: UserWa
rning: Module pixel_clusterizer was already imported from c:\users\jejan\dev\pix
el_clusterizer\pixel_clusterizer\__init__.pyc, but c:\users\jejan\miniconda2\lib
\site-packages\pixel_clusterizer-3.1.2-py2.7.egg is being added to sys.path
  __version__ = get_distribution('pixel_clusterizer').version```

**Comment by DavidLP** [comment]
How can a `tar.gz` package (that I guess you installed with `pip` for checking) look up you dev code? Looks like python package installed not correctly.

**Comment by laborleben** [comment]
It happens when pip is downloading and installing pixel_clusterizer during installation of other packages (e.g., testbeam_analysis). The warnings will not occur, if pixel_clusterizer was installed manually beforehand.

**Comment by DavidLP** [comment]
Is this fixed now?

**Comment by laborleben** [comment]
No, I cannot reproduce anymore. Closing the issue.
