### ISSUE TITLE
how is event_number supposed to be used?

### ISSUE THREAD

**Issue by ozel** [SiLab-Bonn/pixel_clusterizer#15]
I've started using your excellent library for fast analysis of Timepix pixel clusters. So far I'm using 'frame' to identify separate sets of simultaneously recorded pixels (i.e. a monotonically increasing number). 
But how is 'event_number' supposed to be used? I tried assuming it represents something like arrival time (e.g. a TOA timestamp from Timepix1 or 3) but it's not behaving as expected. Also when looking at the code base I can't really see what it is meant to achieve.

**Comment by laborleben** [comment]
We use event_number to identify sets of hits which belong to the same event (= something that triggered the readout). The event_number is unique for a set of hits and is monotonically increasing.

A frame is a subset of an event. It is optionally. The clusterizer allows for clustering in column space, row space, and frame space (e.g., time space).

Is it more clear to you?

**Comment by DavidLP** [comment]
The are also examples that might help: https://github.com/SiLab-Bonn/pixel_clusterizer/tree/master/examples

**Comment by DavidLP** [comment]
If in your definition a frame is the data of one event I recommend using the frame number as the event_number. Can you tell me what hit data fields you have (=the data type of your hits)?

**Comment by ozel** [comment]
Thank's for the quick replies. 
I tried using event_number as well instead of frame but didn't get expected results. The Timepix chip is a pretty different animal from what I guess you designed this library for (large area, multi-layer HEP pixel detectors?). Mine has a matrix of 256 x 256 pixels, it's a single hybrid chip assembly with a readout system that fits easily on my desk ;). The pixels can report charge (TOT) or arrival time (TOA) and recording happens within a certain 'shutter period' (like an exposure time; a repetitive fixed trigger as you may see it). After that time, the whole matrix is read as a single frame, then being again 'exposed', read etc... for a specified number of repetitions ('serial exposures'). This increasing count is my frame number at the moment while keeping event_number at zero.
In your case, does the frame variable enumerate chips being next to each other to cover cases where events spread (laterally) across more than one chip?
I looked at the examples, but they don't help me with understanding your use case and the meaning of the two variables (I haven't worked so far with HEP detector pixel analysis). 
To make things more complex, I plan to extend your library to be compatible with a 'trigger-less', even-based mode that the newer Timepix3 chip supports. There is no exposure time nor external triggering involved in that mode, single pixel hits are sent of chip once the amount of charge is above the set threshold (some bandwidth limitations do of course apply) with TOT and TOA being reported simultaneously for every hit pixel. In that mode, the concept of a frame counter doesn't exist anymore and TOA must be used to find clusters and correlate pixels. Depending on before or after energy calibration, TOT and TOA are either several bits wide integers or floats.
If both frame and event_number are related to time space, is one of them maybe a major scale and the other a minor division of it?
FYI, here's an older [presentation about Timepix] (https://indico.cern.ch/event/3062/contributions/704500/attachments/582541/801876/XavierLlopart_VCI2007.pdf).
There are also many papers on this family of hybrid pixel detector chips.

**Comment by laborleben** [comment]
I'm not familiar with the Timepix3 output data format, but I'm quite sure that there must exist any event structure. This can be a full frame (rolling shutter readout) or some other entity (you named it, 'shutter period') that includes a set of hits. This would make an event.
But you're free to contribute to/modify our package and change it according to your needs. References are also welcome :-)
