### ISSUE TITLE
Additional hit fields are not set in clustered hits

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pixel_clusterizer#5]
Let's define 
``` python
hit_data_type = [
    ('event_number', '<i8'),
    ('frame', '<u1'),
    ('column', '<u4'),
    ('row', '<u4'),
    ('charge', '<u1'),
    ('new_col', '<i4')]
```

and initialize clusterizer:
``` python
clusterizer = HitClusterizer()
clusterizer.set_hit_dtype(np.dtype(hit_data_type))
hits = np.ones((1,), dtype=hit_data_type)
cluster_hits, clusters = clusterizer.cluster_hits(hits)
```
Any value in column "new_col" of `cluster_hits` is 0 even if `hits` has 1 everywhere.

The values are not copied from `hits` array to the new `cluster_hits` array.

**Comment by laborleben** [comment]
@DavidLP : Can you check? The interface was not touched. The assignment of dtypes and column name mappings should be more failsafe.

**Comment by DavidLP** [comment]
Well spotted. A so far not used and tested use case.
